server:
  port: 8080
spring:
  application:
    name: API-GATEWAY-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
#  cloud:
#    discovery:
#      enabled: true
  cloud:
    gateway:
      routes:
        filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 500
              redis-rate-limiter.burstCapacity: 1000
              redis-rate-limiter.requestedTokens: 1
#        filters:
#          - name: CircuitBreaker
#            args:
#              name: CUSTOMER-SERVICE
#              fallbackuri: forward:/customerServiceFallBack
#              name: ACCOUNT-SERVICE
#              fallbackuri: forward:/accountServiceFallBack

#    gateway:
#      routes:
#        - id: v1
#          uri: http://localhost:8081
#          predicates:
#            - Path= /customers/**
#        - id: v2
#          uri: http://localhost:8082
#          predicates:
#            - Path= /products/**
