server:
  port: 8083

spring:
  application:
    name: CUSTOMER-SERVICE

eureka:
  client:
    serviceUrl:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true



