spring:
  application:
    name: WEB-APPLICATION-CONSUMER
  config:
    import: configserver:http://localhost:9296

server:
  port: 6464

eureka:
  client:
    serviceUrl:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
ribbon:
  http:
    client:
      enabled: true
